version: "3"
services:

  db1:
    image: peterbourgon/tns-db
  db2:
    image: peterbourgon/tns-db
    links:
      - db1
  db3:
    image: peterbourgon/tns-db
    links:
      - db1
      - db2

  app1:
    image: peterbourgon/tns-app
    links:
      - db1
      - db2
      - db3
  app2:
    image: peterbourgon/tns-app
    links:
      - db1
      - db2
      - db3

  lb1:
    image: peterbourgon/tns-lb
    links:
      - app1
      - app2
    ports:
      - 0.0.0.0:8001:80
  lb2:
    image: peterbourgon/tns-lb
    links:
      - app1
      - app2
    ports:
      - 0.0.0.0:8002:80

networks:
  default:
    external:
      name: net1
      